apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongo-db
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo
          imagePullPolicy: Always
          env:
            -
              name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            -
              name: MONGO_INITDB_ROOT_PASSWORD
              value: password123
          ports:
            -
              containerPort: 27017
              name: mongodb
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - name: pv
              mountPath: /mnt/data
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: mongodb-pvc