apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
spec:
  storageClassName: mongodb-storageclass
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: name
          operator: In
          values:
            - node1